  export const ClassData = [
    {
      className: 'Intro to Comp Sci I',
      classCode: 'CS 31',
      instructor: '',
      prereq: '',
      completed: true,
  },
  {
      className: 'Intro to Comp Sci II',
      classCode: 'CS 32',
      instructor: '',
      prereq: ['CS 31'],
      completed: true,
  },
  {
      className: 'Intro to Comp Organization',
      classCode: 'CS 33',
      instructor: '',
      prereq: ['CS 32'],
      completed: false,
  },
  {
      className: 'Software Construction',
      classCode: 'CS 35L',
      instructor: '',
      prereq: ['CS 31'],
      completed: false,
  },
  {
      className: 'Logic Design of Digital Systems',
      classCode: 'CS M51A or ECE M16',
      instructor: '',
      prereq: '',
      completed: false,
  },
  {
      className: 'Differential and Inegral Calculus',
      classCode: 'Math 31A',
      instructor: '',
      prereq: ['CS 31'],
      completed: false,
  },
  {
      className: 'Integration and Infinite Series',
      classCode: 'Math 31B',
      instructor: '',
      prereq: ['Math 31A'],
      completed: false,
  },
  {
      className: 'Integration and Infinite Series',
      classCode: 'Math 31B',
      instructor: '',
      prereq: ['Math 31A'],
      completed: false,
  },
  {
      className: 'Calculus of Several Variables',
      classCode: 'Math 32A',
      instructor: '',
      prereq: ['Math 31A'],
      completed: false,
  },
  {
      className: 'Calculus of Several Variables',
      classCode: 'Math 32B',
      instructor: '',
      prereq: ['Math 31B', 'Math 32A'],
      completed: false,
  },
    {
      className: 'Integration and Infinite Series',
      classCode: 'Math 33A',
      instructor: '',
      prereq: ['Math 31B'],
      completed: false,
    },
    {
      className: '',
      classCode: 'Math 33B',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Math 61',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Physics 1A',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Physics 1B',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Physics 1C',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Physics 4AL or 4BL',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS 111',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS 118',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS 131',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS M151B or ECE M116C',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS M152A or ECE M116L',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS 180',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS 181',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS 130 or 152B',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Statisitics (Stats 100A, Math 170A, Math 170E ECE 131A, CEE 110)',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS Upper Div Elective #1 (CS 100-188)',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS Upper Div Elective #2 (CS 100-188)',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS Upper Div Elective #3 (CS 100-187)',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS Upper Div Elective #4 (CS 100-187)',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'CS Upper Div Elective #5 (CS 100-187)',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'TBR #1',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'TBR #2',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'TBR #3',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Sci-Tech #1',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Sci-Tech #2',
      instructor: '',
      prereq: [''],
      completed: false,
    },
    {
      className: '',
      classCode: 'Sci-Tech #3',
      instructor: '',
      prereq: [''],
      completed: false,
    },
  ];
  