/*
    ClassType field specifies the type of class
        - Used to categorize classes so that we could display classes in divided sections
    
    LowerDiv: Lower division Class (listed as preparation for Major courses)
    UpperDiv: Upper division CS class (Major courses)
    SciTech: Science and Technology Class
    TechBreadth: Technical Breadth area class
    Elective: CS Upper Div elective class ( CS 100 - 187)
*/

export const ClassData = [
    {
        className: 'Intro to Comp Sci I',
        classCode: 'CS 31',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Intro to Comp Sci II',
        classCode: 'CS 32',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['CS 31'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Intro to Comp Organization',
        classCode: 'CS 33',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['CS 32'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Software Construction',
        classCode: 'CS 35L',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['CS 31'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Logic Design of Digital Systems',
        classCode: 'CS M51A or ECE M16',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Differential and Inegral Calculus',
        classCode: 'Math 31A',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['CS 31'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Integration and Infinite Series',
        classCode: 'Math 31B',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['Math 31A'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Integration and Infinite Series',
        classCode: 'Math 31B',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['Math 31A'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Calculus of Several Variables',
        classCode: 'Math 32A',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['Math 31A'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Calculus of Several Variables',
        classCode: 'Math 32B',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['Math 31B', 'Math 32A'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Integration and Infinite Series',
        classCode: 'Math 33A',
        classType: 'LowerDiv',
        availability: true,
        prereq: ['Math 31B'],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Differential Equations',
        classCode: 'Math 33B',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Introduction to Discrete Structures',
        classCode: 'Math 61',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Physics for Scientists and Engineers: Mechanics',
        classCode: 'Physics 1A',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Physics for Scientists and Engineers: Oscillations, Waves, Electric and Magnetic ',
        classCode: 'Physics 1B',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Physics for Scientists and Engineers: Electrodynamics, Optics, and Special Relativity',
        classCode: 'Physics 1C',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: 'Physics Laboratory for Scientists and Engineers',
        classCode: 'Physics 4AL or 4BL',
        classType: 'LowerDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS 111',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS 118',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS 131',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS M151B or ECE M116C',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS M152A or ECE M116L',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS 180',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS 181',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS 130 or 152B',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'Statisitics (Stats 100A, Math 170A, Math 170E ECE 131A, CEE 110)',
        classType: 'UpperDiv',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS Upper Div Elective #1 (CS 100-188)',
        classType: 'Elective',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS Upper Div Elective #2 (CS 100-188)',
        classType: 'Elective',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS Upper Div Elective #3 (CS 100-187)',
        classType: 'Elective',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS Upper Div Elective #4 (CS 100-187)',
        classType: 'Elective',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'CS Upper Div Elective #5 (CS 100-187)',
        classType: 'Elective',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'TBR #1',
        classType: 'TechBreadth',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'TBR #2',
        classType: 'TechBreadth',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'TBR #3',
        classType: 'TechBreadth',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'Sci-Tech #1',
        classType: 'SciTech',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'Sci-Tech #2',
        classType: 'SciTech',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    {
        className: '',
        classCode: 'Sci-Tech #3',
        classType: 'SciTech',
        availability: true,
        prereq: [],
        completed: false,
        grade: 0,
        units: 3,
        description: '',
    },
    ];